server.port=8082
spring.application.name=inventory-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.cloud.aws.sqs.endpoint=${AWS_SQS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
spring.cloud.aws.endpoint-override=${AWS_CLOUDWATCH_ENDPOINT:http://localhost:4566}
spring.cloud.aws.logs.endpoint=${AWS_CLOUDWATCH_ENDPOINT:http://localhost:4566}

app.sqs.shipping-queue=${SHIPPING_QUEUE:shipping-queue}

# CloudWatch Logs
logging.level.root=INFO
logging.level.com.smartlogix=DEBUG
spring.cloud.aws.logs.enabled=true

# CloudWatch Metrics
management.metrics.export.cloudwatch.enabled=true
management.metrics.export.cloudwatch.namespace=SmartLogix
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,metrics,prometheus

# Actuator endpoints
management.endpoint.health.show-details=always

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger