AWSTemplateFormatVersion: '2010-09-09'
Description: SmartLogix ECR repositories for microservices.

Resources:
  OrdersRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: orders-service
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  InventoryRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: inventory-service
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  ShippingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: shipping-service
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  NotificationRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: notification-service
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  OrdersRepositoryUri:
    Value: !GetAtt OrdersRepository.RepositoryUri
  InventoryRepositoryUri:
    Value: !GetAtt InventoryRepository.RepositoryUri
  ShippingRepositoryUri:
    Value: !GetAtt ShippingRepository.RepositoryUri
  NotificationRepositoryUri:
    Value: !GetAtt NotificationRepository.RepositoryUri
