server.port=8083
spring.application.name=identity-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/identity_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}

# Actuator endpoints
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
